/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.connPos;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class editaPlanta extends javax.swing.JFrame {

      String cod_planta=" ";
      int cod_region=0;
    /**
     * Creates new form editaPlanta
     */
    public editaPlanta() {
        initComponents();
       
    }
    
    public editaPlanta(String cod_planta,int cod_region,String nombre_nativo,String nombre_cientifico,
                              String tipo_planta,String color_planta,String mes_semilla,String nro_de_registro_planta,
                              String fecha_registro,String fuente_de_datos,String idioma_region,String tipo_uso,String parte_uso,
                              String manera_uso,String descripcion_pla) {
        
        initComponents();
        this.cod_planta=cod_planta;
        this.cod_region=cod_region;
        this.EPNomNat.setText(nombre_nativo);
        this.EPNomCie.setText(nombre_cientifico);
        this.EPEsp.setText(tipo_planta);
        this.EPCol.setText(color_planta);
        this.EPTipUso.setText(mes_semilla);
        this.EPPartUso.setText(nro_de_registro_planta);
        this.EPManUso.setText(fecha_registro);
        this.EPDesp.setText(fuente_de_datos);
        this.EPDesAni.setText(idioma_region);
        this.EPNumReg.setText(tipo_uso);
        this.EPFec.setText(parte_uso);
        this.EPFue.setText(manera_uso);
        this.EPIdi.setText(descripcion_pla); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EPNomNat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EPNomCie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EPEsp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EPCol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EPTipUso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EPPartUso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EPManUso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EPDesp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EPDesAni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EPNumReg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        EPFec = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        EPFue = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        EPIdi = new javax.swing.JTextField();
        btnActualizarPlanta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("NOMBRE NATIVO :");

        jLabel3.setText("NOMBRE CIENTIFICO :");

        EPNomCie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPNomCieActionPerformed(evt);
            }
        });

        jLabel4.setText("TIPO DE PLANTA :");

        jLabel5.setText("COLOR :");

        jLabel6.setText("MES DE PRODUCCION DE LA SEMILLA :");

        jLabel7.setText("NRO.  DE REGISTRO :");

        jLabel8.setText("FECHA DE REGISTRO :");

        jLabel9.setText("FUENTE DE DATOS :");

        jLabel10.setText("IDIOMA :");

        jLabel11.setText("NUMERO DE REGISTRO :");

        jLabel12.setText("TIPO DE USO :");

        jLabel13.setText("PARTE DE USO :");

        jLabel14.setText("MANERA DE USO :");

        btnActualizarPlanta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizarPlanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnActualizarPlanta.setText("ACTUALIZAR ");
        btnActualizarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EPNomNat)
                        .addComponent(EPNomCie)
                        .addComponent(EPEsp)
                        .addComponent(EPCol)
                        .addComponent(EPTipUso)
                        .addComponent(EPPartUso)
                        .addComponent(EPDesp)
                        .addComponent(EPManUso)
                        .addComponent(EPDesAni)
                        .addComponent(EPNumReg)
                        .addComponent(EPFec)
                        .addComponent(EPFue, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EPIdi, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnActualizarPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(EPNomNat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EPNomCie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EPEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EPCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EPTipUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EPPartUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EPManUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(EPDesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EPDesAni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EPNumReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EPFec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EPFue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(EPIdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnActualizarPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EPNomCieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPNomCieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPNomCieActionPerformed

    private void btnActualizarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPlantaActionPerformed
        
         connPos cn= new connPos();
        
        String nombre_nativo=this.EPNomNat.getText().toString();
        String nombre_cientifico=this.EPNomCie.getText().toString();
        String tipo_planta=this.EPEsp.getText().toString();
        String color_planta=this.EPCol.getText().toString();
        String mes_semilla=this.EPTipUso.getText().toString();
        String nro_de_registro_planta=this.EPPartUso.getText().toString();
        String fecha_registro=this.EPManUso.getText().toString();
        String fuente_de_datos=this.EPDesp.getText().toString();
        String idioma_region=this.EPDesAni.getText().toString();
        String tipo_uso=this.EPNumReg.getText().toString();
        String parte_uso=this.EPFec.getText().toString();
        String manera_uso=this.EPFue.getText().toString();
        String descripcion_pla=this.EPIdi.getText().toString();
        
        cn.actualizarPlanta(cod_planta,cod_region,nombre_nativo,nombre_cientifico,tipo_planta,color_planta,mes_semilla,
                            nro_de_registro_planta,fecha_registro,fuente_de_datos,idioma_region,tipo_uso,parte_uso,
                            manera_uso,descripcion_pla);
        //cn.cerrarConexion();
        JOptionPane.showMessageDialog(rootPane,"Registro Actualizado");
        this.dispose();
        Animales ani=new Animales();
        ani.setVisible(true);
        
    }//GEN-LAST:event_btnActualizarPlantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editaPlanta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EPCol;
    private javax.swing.JTextField EPDesAni;
    private javax.swing.JTextField EPDesp;
    private javax.swing.JTextField EPEsp;
    private javax.swing.JTextField EPFec;
    private javax.swing.JTextField EPFue;
    private javax.swing.JTextField EPIdi;
    private javax.swing.JTextField EPManUso;
    private javax.swing.JTextField EPNomCie;
    private javax.swing.JTextField EPNomNat;
    private javax.swing.JTextField EPNumReg;
    private javax.swing.JTextField EPPartUso;
    private javax.swing.JTextField EPTipUso;
    private javax.swing.JButton btnActualizarPlanta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
